// add things that needed for each card here
export const boardBeforeRandomized = [
	{ value: 100, shown: true, flip: false, flash: false },
	{ value: 100, shown: true, flip: false, flash: false },
	{ value: 100, shown: true, flip: false, flash: false },
	{ value: 100, shown: true, flip: false, flash: false },
	{ value: 125, shown: true, flip: false, flash: false },
	{ value: 125, shown: true, flip: false, flash: false },
	{ value: 125, shown: true, flip: false, flash: false },
	{ value: 125, shown: true, flip: false, flash: false },
	{ value: 150, shown: true, flip: false, flash: false },
	{ value: 150, shown: true, flip: false, flash: false },
	{ value: 150, shown: true, flip: false, flash: false },
	{ value: 150, shown: true, flip: false, flash: false },
	{ value: 175, shown: true, flip: false, flash: false },
	{ value: 175, shown: true, flip: false, flash: false },
	{ value: 175, shown: true, flip: false, flash: false },
	{ value: 175, shown: true, flip: false, flash: false },
	{ value: 200, shown: true, flip: false, flash: false },
	{ value: 200, shown: true, flip: false, flash: false },
	{ value: 200, shown: true, flip: false, flash: false },
	{ value: 200, shown: true, flip: false, flash: false },
	{ value: 210, shown: true, flip: false, flash: false },
	{ value: 210, shown: true, flip: false, flash: false },
	{ value: 220, shown: true, flip: false, flash: false },
	{ value: 220, shown: true, flip: false, flash: false },
	{ value: 250, shown: true, flip: false, flash: false },
	{ value: 250, shown: true, flip: false, flash: false },
	{ value: "bomb", shown: true, flip: false, flash: false },
	{ value: "bomb", shown: true, flip: false, flash: false },
	{ value: "bomb", shown: true, flip: false, flash: false },
	{ value: "bomb", shown: true, flip: false, flash: false },
];
