services:
  flip-and-boom:
    build: ./
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - DATABASE_URL=${DATABASE_URL}